### ISSUE TITLE
answers: add 'closed questions' dataseries to Overall statistics

### ISSUE THREAD

**Issue by gavanderhoorn** [DLu/ros_metrics#13]
Currently the plot only shows total (Q&A), answered and answered ratio.

It would be nice if we could also see the nr of closed questions.

**Comment by gavanderhoorn** [comment]
Something to consider -- if it's not already done that way: subtract 'closed' from 'unanswered'.

**Comment by DLu** [comment]
Closed questions have an `accepted_answer_id` of `-1`, so they are considered answered. However, there is sometimes a little lag in marking things as closed/accepted. https://github.com/ASKBOT/askbot-devel/pull/843

**Comment by gavanderhoorn** [comment]
But as it has a different id, we could display it in a separate category, correct?

**Comment by DLu** [comment]
Yup.
