### ISSUE TITLE
Hovering over line charts shows multiple data points per series

### ISSUE THREAD

**Issue by DLu** [DLu/ros_metrics#17]
![example](https://user-images.githubusercontent.com/4550046/71723188-037a3200-2e2c-11ea-981b-749cfc52e215.png)

As raised by @gavanderhoorn in #16. 

Note: Its resolution dependent and the [changes I made to the timepoints](https://github.com/DLu/ros_metrics/pull/16/commits/d59183ba384d2703510e5e20918c9dff6efa6bcc) were meant to mitigate it. If I hadn't done that commit, even more data points per series would be shown.

**Comment by gavanderhoorn** [comment]
Nice one. Thanks :+1:
