### ISSUE TITLE
Users graph starts at Unix Epoch start (1970-01-01)?

### ISSUE THREAD

**Issue by gavanderhoorn** [DLu/ros_metrics#33]
Just happened to notice it (I'm not F5-ing `metrics.ros.org`):

![image](https://user-images.githubusercontent.com/4550046/110452131-2ace2e00-80c5-11eb-9414-9e2ce67f5e7e.png)

**Comment by gavanderhoorn** [comment]
The real mystery though:

![image](https://user-images.githubusercontent.com/4550046/110452289-55b88200-80c5-11eb-9f2e-79d0b7430ea5.png)

who started working on ROS in 1999?

**Comment by DLu** [comment]
I thought I had put a guard in place to remove older commits, but maybe that's on some other branch. 

It may be the case that "someone" put a [placeholder commit](https://github.com/locusrobotics/robot_navigation/commit/a52751dc79ce94ab5728bb7850ab5a8415bf2642) in their repository while they were finishing their ROSCon talk on the subject, and thought it would be funny to backdate it, and now that person is reaping what they sow.

**Comment by gavanderhoorn** [comment]
> It may be the case that "someone" put a placeholder commit in their repository

yeah, those "someones" ..
