### ISSUE TITLE
answers: "closed questions" statistic the same value since 2019-09-30?

### ISSUE THREAD

**Issue by gavanderhoorn** [DLu/ros_metrics#39]
Looking at [metrics.ros.org/answers_questions.html](https://metrics.ros.org/answers_questions.html), it seems the *closed questions* statistic has been at the value of `3692` since `2019-09-30`:

![image](https://github.com/DLu/ros_metrics/assets/4550046/5e4f072b-d77b-4188-9e11-d6e41fdfbcec)

notice the curve at the bottom which seems to become 'flat' around the 2020 marker. The curves for the other statistics also seem to have an inflection point around that same time.

**Comment by DLu** [comment]
Bug found. PR and new metrics after I finish scraping the updated data.
