### ISSUE TITLE
Overlay vertical line on plots with multiple dataseries

### ISSUE THREAD

**Issue by gavanderhoorn** [DLu/ros_metrics#9]
Not sure how to describe this better, but I'm thinking of a vertical line which follows the mouse cursor when hovering over a plot and shows that values of all dataseries plotted at that particular X value.

On [](https://metrics.ros.org/answers_questions.html) fi this would show the total nr of questions, nr of answered and open questions and percentage at the same time, instead of having to hover over all plots separately.

**Comment by DLu** [comment]
Would something like this work: https://www.chartjs.org/samples/latest/tooltips/custom-points.html

**Comment by gavanderhoorn** [comment]
Yes, that's exactly what I was thinking of.

Doesn't draw an actual line, but that is not too important.
